# Generated by Django 4.2.9 on 2024-02-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('DELIVERY', 'Delivery Agent')], default='ADMIN', max_length=10),
        ),
    ]
