# Generated by Django 4.2.9 on 2024-01-17 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canteen_manager', '0002_foodcategory_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanteenManaer',
            new_name='CanteenManager',
        ),
        migrations.AddField(
            model_name='food',
            name='is_todays_special',
            field=models.BooleanField(default=False),
        ),
    ]
