# Generated by Django 4.2.9 on 2024-01-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_manager', '0003_rename_canteenmanaer_canteenmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
