# Generated by Django 4.2.9 on 2024-02-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_manager', '0005_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
