ERROR_MSG = "Something went wrong.Please contact the administrator."
NOT_CANTEEN_MANAGER_MSG = "You Should be a CANTEEN MANAGER to access this API"
NOT_TEACHER_MSG = "You Should be a TEACHER to access this API"
NOT_STUDENT_MSG = "You Should be a STUDENT to access this API"
DUMMY_IMAGE_PLACEHOLDER = "https://iconicentertainment.in/wp-content/uploads/2013/11/dummy-image-square.jpg"