# Generated by Django 4.2.9 on 2024-02-19 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_agent', '0001_initial'),
        ('student', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_agent.deliveryagent'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('APPROVED', 'Order Approved'), ('REJECTED', 'Order Rejected'), ('READY', 'Order Ready To be Delivered'), ('PICKED', 'Order Picked By Delivery Agent'), ('DELIVERED', 'Order Delivered')], default='PLACED', max_length=100),
        ),
    ]
